## Test 3.0


In [2]:
num = int(input("Enter the number:"))
if num % 2 == 0:
    print("Number is Even")
else:
    print("Number is Odd")

Enter the number:4
Number is Even


In [5]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [8]:
while True:
    num = int(input("Enter a Number: "))
    if num == 0:
        break

   

Enter a Number: 5
Enter a Number: 4
Enter a Number: 0


In [9]:
def add_two_num(a,b):
    return a+b
add_two_num(5,5)

10

In [ ]:
What will be the output of this code: print(list(map(lambda x: x*x, [1, 2, 3])))?

In [10]:
print(list(map(lambda x: x*x, [1, 2, 3])))

[1, 4, 9]


In [12]:
num = [1,2,3,4,5,6,7,8,9]
even_num  = list(filter(lambda x: x %2 == 0, num))
print(even_num)

[2, 4, 6, 8]


Explain the purpose of the else block in a try-except-else construct.

In [13]:
# Else block runs only when if no xception occurs in the try block

In [14]:
try:
    10/0
except ZeroDivisionError:
    print("We can't divide by zero")

We can't divide by zero


In [ ]:
# 8

In [15]:
class Dog:
    def __init__(self,name,breed):
        self.name = name
        self.breed = breed
    def bark(self):
        print(self.name)
        

In [16]:
dog1 = Dog("Dog1", "xyz")
dog = Dog("Dog2", "pqr")
dog1.bark()
dog2.bark()

Dog1
Dog2


In [ ]:
# Class Variable : Shared across all instances of the class
# Instance Veriable : Unique to each object

In [ ]:
apple

In [19]:
def square(l):
    return[i*i for i in l]
square([1,2,3,4])

[1, 4, 9, 16]

In [ ]:
# map() Returns the map objecte that applies a function to each itemin an iterable
# filter() Return a filter object containing elementes from the iterable for which the function returns True

### Numpy

In [21]:
import numpy as np
mat = np.random.randint(0, 10, (3, 3))
print(mat)

[[6 4 3]
 [4 2 5]
 [5 1 7]]


In [24]:
print(mat[:2])

[[6 4 3]
 [4 2 5]]


Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.

In [26]:
mat1 = np.random.randint(0,10,(3,3))
print(np.concatenate((mat,mat1),axis=0))
print(np.concatenate((mat,mat1),axis=1))

[[6 4 3]
 [4 2 5]
 [5 1 7]
 [3 0 9]
 [3 4 6]
 [3 9 8]]
[[6 4 3 3 0 9]
 [4 2 5 3 4 6]
 [5 1 7 3 9 8]]


In [32]:
print("Addition of two matrics\n",mat+mat1)
print("Subtraction of two matrics\n",mat-mat1)
print("Multiplicatin of two matrics\n",mat*mat1)

Addition of two matrics
 [[ 9  4 12]
 [ 7  6 11]
 [ 8 10 15]]
Subtraction of two matrics
 [[ 3  4 -6]
 [ 1 -2 -1]
 [ 2 -8 -1]]
Multiplicatin of two matrics
 [[18  0 27]
 [12  8 30]
 [15  9 56]]


In [37]:
a_array = np.array([1,2,3])
b_array = np.array([[4,5,6],[7,8,9]])
print(a_array + b_array)

[[ 5  7  9]
 [ 8 10 12]]


In [39]:
a = np.random.randint(0, 10, (3, 3))
print(np.clip(a,2,8))

[[8 8 2]
 [6 7 7]
 [6 5 3]]


In [43]:
print(np.ceil([1.2, 2.5, 3.8]))

[2. 3. 4.]


In [49]:
arr = np.array([1,2,3,5,6,9])
print( np.where(arr>5,100,arr))


[  1   2   3   5 100 100]


In [50]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
np.array([1, 2, 3]) #It is 1-D arry
np.array([[1, 2, 3]]) # It is 2 D arry